
# OpenShift Lab environment details

targetenv:
  guid: 
  bastion_host: 
  bastion_user: 
  bastion_pass: 
  ocp:
    console: 
    api: "https://api.ocp.example.com:6443"
    user: developer
    pass: 


